name: Backend tasks

on:
  push:
    branches:
      - '**'

jobs:
  build_test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9.6' 

      - name: Install Poetry and project
        run: |
          pip install poetry==1.1.10
          cd backend
          poetry install
      
      - name: Build project
        run: cd backend && poetry run poe build
      
      - name: Test project
        run: cd backend && poetry run poe test
      
      - name: Lint project
        run: cd backend && poetry run poe lint
      
      - name: Type Check project
        run: cd backend && poetry run poe type-check
